version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rappidu
      MONGO_DB_USERNAME: myuser
      MONGO_DB_PASSWORD: senha


  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rappidu-cadastro
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mongodb
