spring:
  data:
    mongodb:
       port: 27017
       database: rappidu
       host: localhost
       auto-index-creation: true


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG

